// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxhjfhdfbbttwppnoxln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4aGpmaGRmYmJ0dHdwcG5veGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDg0OTMsImV4cCI6MjA3MzUyNDQ5M30.j2p8w8x1qVIycOveJsoVT1vMzNlrrVNYqT7gNtHImw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});